# ======================================================
# Data configuration
# ======================================================
data:
  img_size: 224
  channels: 3
  seed: 42
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1


# ======================================================
# Training configuration – Local (Windows)
# Used for M1 model development & MLflow tracking
# ======================================================
local:
  batch_size: 16
  epochs: 1          # Used for FINAL model
  learning_rate: 0.001
  num_workers: 0
  use_augmentation: true


# ======================================================
# Training configuration – OSHA (Linux VM)
# Not used for M1 training, kept for completeness
# ======================================================
osha:
  batch_size: 32
  epochs: 1
  learning_rate: 0.0003
  num_workers: 4
  use_augmentation: true


# ======================================================
# Baseline configuration (explicit for grading)
# ======================================================
baseline:
  epochs: 3            # Short run for baseline comparison
  freeze_backbone: true
  use_augmentation: false


# ======================================================
# Model configuration
# ======================================================
model:
  architecture: mobilenet_v2
  pretrained: true
  freeze_backbone: false   # Overridden in baseline run
  num_classes: 2
